### ISSUE TITLE
2.12.2 failed build

### ISSUE THREAD

**Issue by rmorgans** [direnv/direnv-archlinux#4]
Hi @zimbatm - I just updated the pkgver and the sha

it seems to fail on a build for some reason - it looks like it can't find a dotenv package. Any ideas how to build?

Many thanks

Rick

```
 ==> Starting build()...
go fmt
go build  -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/direnv/dotenv" in any of:
        /usr/lib/go/src/github.com/direnv/direnv/dotenv (from $GOROOT)
        /local/packages/direnv-archlinux/src/src/github.com/direnv/direnv/dotenv (from $GOPATH)
make: *** [Makefile:37: direnv] Error 1

```

**Comment by zimbatm** [comment]
Hi @rmorgans, the issue is that direnv now has dependencies and so needs to be checked out into `$GOPATH/src/github.com/direnv/direnv`. This is fairly standard with go packages so there should be examples around in AUR.

**Comment by zimbatm** [comment]
I had a look at https://wiki.archlinux.org/index.php/Go_package_guidelines but none of the solutions are very satisfying.

I think the best option would be to create and move the source in [`prepare()`](https://wiki.archlinux.org/index.php/Creating_packages#prepare.28.29)

**Comment by zimbatm** [comment]
Do you mind testing this? https://github.com/direnv/direnv-archlinux/pull/5
